# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  packages: write
  pull-requests: write
  id-token: write
  actions: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - &cache-nix-store
        name: Cache Nix Store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}

      - name: Run Nix checks
        run: nix flake check -L

  build:
    name: Build ${{ matrix.arch }} Image
    needs: [test]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runs-on: ubuntu-24.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/main'))
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - *cache-nix-store

      - name: Build ${{ matrix.arch }} image
        run: |
          nix build .#ffmpeg --out-link result-${{ matrix.arch }} -L
          cp -L result-${{ matrix.arch }} result-${{ matrix.arch }}.tar.gz

      - name: Upload ${{ matrix.arch }} artifact
        uses: actions/upload-artifact@v7
        with:
          name: image-${{ matrix.arch }}
          path: result-${{ matrix.arch }}.tar.gz
          if-no-files-found: error
          retention-days: 1

  push-multiarch:
    name: Push Multi-Arch Image
    needs: [build]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - *cache-nix-store

      - name: Download AMD64 artifact
        uses: actions/download-artifact@v8
        with:
          name: image-amd64
          path: artifacts-amd64

      - name: Download ARM64 artifact
        uses: actions/download-artifact@v8
        with:
          name: image-arm64
          path: artifacts-arm64

      - name: Get ffmpeg version
        id: ffmpeg-version
        run: echo "version=$(nix eval --raw .#ffmpeg.imageTag)" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/ffmpeg
          tags: |
            type=raw,value=${{ steps.ffmpeg-version.outputs.version }}
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬆️ Push Multi-Arch Image to GHCR
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          nix run .#push-multiarch -- "ghcr.io/${{ github.repository_owner }}/ffmpeg" artifacts-amd64/result-amd64.tar.gz artifacts-arm64/result-arm64.tar.gz
